language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g Financial-Times/origami-build-tools#node-0.10
  - origami-build-tools install
script:
  - origami-build-tools test
  - origami-build-tools verify
